CREATE DATABASE IF NOT EXISTS strydb;

DROP TABLE IF EXISTS strydb.account;

CREATE TABLE IF NOT EXISTS strydb.account (
	id INT(12) AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(200),
	date_joined TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1000;
